package com.tictactoe.engine.gui;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.tictactoe.engine.Alliance;
import com.tictactoe.engine.board.Board;
import com.tictactoe.engine.player.OPlayer;
import com.tictactoe.engine.player.XPlayer;

import javax.swing.*;
import java.awt.*;

import static com.tictactoe.engine.board.BoardUtils.allianceTank;
import static com.tictactoe.engine.board.BoardUtils.playTank;
import static com.tictactoe.engine.board.Tile.EMPTY_TILE_CACHE;
import static com.tictactoe.engine.gui.ExecutionGui.link;

/**
 *
 * @author kali
 */
public class LayOut extends javax.swing.JFrame {

    protected static Board board;
    public final static Settings settings = new Settings();
    protected final static XPlayer xPlayer = XPlayer.getInstance();
    protected final static OPlayer oPlayer = OPlayer.getInstance();

    /**
     * Creates new form xoFrame
     */
    public LayOut() {
        board = Board.newBoard(EMPTY_TILE_CACHE);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblXScore = new javax.swing.JLabel();
        lblOScore = new javax.swing.JLabel();
        lblGameScore = new javax.swing.JLabel();
        lblxscore = new javax.swing.JLabel();
        lbloscore = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TicTacoo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(23, 23, 23));

        jPanel1.setBackground(new java.awt.Color(23, 23, 23));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        btn1.setBackground(new java.awt.Color(23, 23, 23));
        btn1.setFont(new java.awt.Font("Dialog", Font.PLAIN, 100)); // NOI18N
        btn1.setForeground(new java.awt.Color(254, 254, 254));
        btn1.addActionListener(this::btn1ActionPerformed);
        jPanel1.add(btn7);

        btn4.setBackground(new java.awt.Color(23, 23, 23));
        btn4.setFont(new java.awt.Font("Dialog", Font.PLAIN, 100)); // NOI18N
        btn4.setForeground(new java.awt.Color(254, 254, 254));
        btn4.addActionListener(this::btn4ActionPerformed);
        jPanel1.add(btn8);

        btn7.setBackground(new java.awt.Color(23, 23, 23));
        btn7.setFont(new java.awt.Font("Dialog", Font.PLAIN, 100)); // NOI18N
        btn7.setForeground(new java.awt.Color(254, 254, 254));
        btn7.addActionListener(this::btn7ActionPerformed);
        jPanel1.add(btn9);

        btn8.setBackground(new java.awt.Color(23, 23, 23));
        btn8.setFont(new java.awt.Font("Dialog", Font.PLAIN, 100)); // NOI18N
        btn8.setForeground(new java.awt.Color(254, 254, 254));
        btn8.addActionListener(this::btn8ActionPerformed);
        jPanel1.add(btn4);

        btn9.setBackground(new java.awt.Color(23, 23, 23));
        btn9.setFont(new java.awt.Font("Dialog", Font.PLAIN, 100)); // NOI18N
        btn9.setForeground(new java.awt.Color(254, 254, 254));
        btn9.addActionListener(this::btn9ActionPerformed);
        jPanel1.add(btn5);

        btn6.setBackground(new java.awt.Color(23, 23, 23));
        btn6.setFont(new java.awt.Font("Dialog", Font.PLAIN, 100)); // NOI18N
        btn6.setForeground(new java.awt.Color(254, 254, 254));
        btn6.addActionListener(this::btn6ActionPerformed);
        jPanel1.add(btn6);

        btn5.setBackground(new java.awt.Color(23, 23, 23));
        btn5.setFont(new java.awt.Font("Dialog", Font.PLAIN, 100)); // NOI18N
        btn5.setForeground(new java.awt.Color(254, 254, 254));
        btn5.addActionListener(this::btn5ActionPerformed);
        jPanel1.add(btn1);

        btn2.setBackground(new java.awt.Color(23, 23, 23));
        btn2.setFont(new java.awt.Font("Dialog", Font.PLAIN, 100)); // NOI18N
        btn2.setForeground(new java.awt.Color(254, 254, 254));
        btn2.addActionListener(this::btn2ActionPerformed);
        jPanel1.add(btn2);

        btn3.setBackground(new java.awt.Color(23, 23, 23));
        btn3.setFont(new java.awt.Font("Dialog", Font.PLAIN, 100)); // NOI18N
        btn3.setForeground(new java.awt.Color(254, 254, 254));
        btn3.addActionListener(this::btn3ActionPerformed);
        jPanel1.add(btn3);

        jPanel2.setBackground(new java.awt.Color(23, 23, 23));

        lblXScore.setBackground(new java.awt.Color(255, 255, 255));
        lblXScore.setFont(new java.awt.Font("eufm10", Font.PLAIN, 15)); // NOI18N
        lblXScore.setForeground(new java.awt.Color(255, 253, 252));
        lblXScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXScore.setText("X score :   ");

        lblOScore.setBackground(new java.awt.Color(255, 255, 255));
        lblOScore.setFont(new java.awt.Font("eufm10", Font.PLAIN, 15)); // NOI18N
        lblOScore.setForeground(new java.awt.Color(255, 253, 252));
        lblOScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOScore.setText("O score :  ");

        lblGameScore.setBackground(new java.awt.Color(255, 255, 255));
        lblGameScore.setFont(new java.awt.Font("eufm10", Font.PLAIN, 15)); // NOI18N
        lblGameScore.setForeground(new java.awt.Color(255, 253, 252));
        lblGameScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGameScore.setText("Game Start");

        lblxscore.setBackground(new java.awt.Color(255, 255, 255));
        lblxscore.setFont(new java.awt.Font("eufm10", Font.PLAIN, 15)); // NOI18N
        lblxscore.setForeground(new java.awt.Color(255, 253, 252));
        lblxscore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblxscore.setText("0");

        lbloscore.setBackground(new java.awt.Color(255, 255, 255));
        lbloscore.setFont(new java.awt.Font("eufm10", Font.PLAIN, 15)); // NOI18N
        lbloscore.setForeground(new java.awt.Color(255, 253, 252));
        lbloscore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbloscore.setText("0");

        jButton1.setBackground(new java.awt.Color(23, 23, 23));
        jButton1.setFont(new java.awt.Font("eufm10", Font.PLAIN, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 253, 252));
        jButton1.setText("Settings");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(lblXScore)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblxscore))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(lblOScore)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lbloscore)
                                                        .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(112, 112, 112)
                                                .addComponent(jButton1)))
                                .addComponent(lblGameScore, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton1))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(lblXScore)
                                                                        .addComponent(lblxscore))
                                                                .addGap(35, 35, 35)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(lblOScore)
                                                                        .addComponent(lbloscore)))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(23, 23, 23)
                                                                .addComponent(lblGameScore, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 16, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();

    }// </editor-fold>

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {
        link(7);
    }

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {
        link(8);
    }

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {
        link(9);
    }

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {
        link(4);
    }

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {
        link(5);
    }

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {
        link(6);
    }

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {
        link(1);
    }

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {
        link(2);
    }

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {
        link(3);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        settings.setVisible(true);
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        playTank.add(board);
        allianceTank.add(Alliance.O);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Dark".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException | InstantiationException ex) {
            java.util.logging.Logger.getLogger(LayOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LayOut().setVisible(true));
    }

    // Variables declaration - do not modify
    public static javax.swing.JButton btn1;
    public static javax.swing.JButton btn2;
    public static javax.swing.JButton btn3;
    public static javax.swing.JButton btn4;
    public static javax.swing.JButton btn5;
    public static javax.swing.JButton btn6;
    public static javax.swing.JButton btn7;
    public static javax.swing.JButton btn8;
    public static javax.swing.JButton btn9;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblGameScore;
    private javax.swing.JLabel lblOScore;
    private javax.swing.JLabel lblXScore;
    private javax.swing.JLabel lbloscore;
    private javax.swing.JLabel lblxscore;
    // End of variables declaration
}
