package com.tictactoe.engine.gui;

import com.tictactoe.engine.player.PlayerType;

import javax.swing.*;
import java.awt.*;

import static com.tictactoe.engine.gui.LayOut.settings;

/**
 *
 * @author kali
 */
public class Settings extends javax.swing.JFrame {

    private PlayerType xPlayerType;
    private PlayerType oPlayerType;
    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
        this.xPlayerType = setXPlayer();
        this.oPlayerType = setOPlayer();
    }

    public PlayerType getXPlayerType() {
        return this.xPlayerType;
    }

    public PlayerType getOPlayerType() {
        return PlayerType.AI;
    }

    private PlayerType setXPlayer() {
        if(rdXAI.isSelected())
            return PlayerType.AI;
        else if(rdXHuman.isSelected())
            return PlayerType.HUMAN;
        return PlayerType.HUMAN;
    }

    private PlayerType setOPlayer() {
        if(rdOAI.isSelected())
            return PlayerType.AI;
        else if(rdOHuman.isSelected())
            return PlayerType.HUMAN;
        return PlayerType.HUMAN;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdXHuman = new javax.swing.JRadioButton();
        rdXAI = new javax.swing.JRadioButton();
        rdOHuman = new javax.swing.JRadioButton();
        rdOAI = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Settings");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(23, 23, 23));

        jLabel1.setFont(new java.awt.Font("Cantarell", Font.BOLD, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 253, 253));
        jLabel1.setText("Player X");

        jLabel2.setFont(new java.awt.Font("Cantarell", Font.BOLD, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 253, 253));
        jLabel2.setText("Player O");

        rdXHuman.setBackground(new java.awt.Color(23, 23, 23));
        rdXHuman.setForeground(new java.awt.Color(255, 253, 253));
        rdXHuman.setText("Human");
        rdXHuman.addActionListener(this::rdXHumanActionPerformed);

        rdXAI.setBackground(new java.awt.Color(23, 23, 23));
        rdXAI.setForeground(new java.awt.Color(255, 253, 253));
        rdXAI.setText("AI");
        rdXAI.addActionListener(this::rdXAIActionPerformed);

        rdOHuman.setBackground(new java.awt.Color(23, 23, 23));
        rdOHuman.setForeground(new java.awt.Color(255, 253, 253));
        rdOHuman.setText("Human");
        rdOHuman.addActionListener(this::rdOHumanActionPerformed);

        rdOAI.setBackground(new java.awt.Color(23, 23, 23));
        rdOAI.setForeground(new java.awt.Color(255, 253, 253));
        rdOAI.setText("AI");
        rdOAI.addActionListener(this::rdOAIActionPerformed);

        btnSave.setBackground(new java.awt.Color(26, 26, 26));
        btnSave.setForeground(new java.awt.Color(255, 253, 253));
        btnSave.setText("Save");
        btnSave.addActionListener(evt -> btnSaveActionPerformed(evt));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(rdOHuman)
                                                        .addComponent(rdOAI)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(jLabel2)
                                                                .addComponent(jLabel1))
                                                        .addComponent(rdXAI)
                                                        .addComponent(rdXHuman)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(61, 61, 61)
                                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(58, Short.MAX_VALUE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(rdXHuman)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdXAI)
                                .addGap(5, 5, 5)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(rdOHuman)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdOAI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(btnSave)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void rdXAIActionPerformed(java.awt.event.ActionEvent evt) {
        rdXHuman.setSelected(false);
        rdXAI.setSelected(true);
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {
        if(rdXHuman.isSelected())
            this.xPlayerType = PlayerType.HUMAN;
        else
            this.xPlayerType = PlayerType.AI;

        if(rdOHuman.isSelected())
            this.oPlayerType = PlayerType.HUMAN;
        else
            this.oPlayerType = PlayerType.AI;

        settings.setVisible(false);
    }

    private void rdOAIActionPerformed(java.awt.event.ActionEvent evt) {
        rdOHuman.setSelected(false);
        rdOAI.setSelected(true);
    }

    private void rdOHumanActionPerformed(java.awt.event.ActionEvent evt) {
        rdOAI.setSelected(false);
        rdOHuman.setSelected(true);
    }

    private void rdXHumanActionPerformed(java.awt.event.ActionEvent evt) {
        rdXAI.setSelected(false);
        rdXHuman.setSelected(true);
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        this.setLocationRelativeTo(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Dark".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rdOAI;
    private javax.swing.JRadioButton rdOHuman;
    private javax.swing.JRadioButton rdXAI;
    private javax.swing.JRadioButton rdXHuman;
    // End of variables declaration
}
